# Generated by Django 4.2 on 2023-04-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseInfo',
            fields=[
                ('enterpriseID', models.AutoField(primary_key=True, serialize=False, verbose_name='企业ID')),
                ('name', models.CharField(max_length=32, verbose_name='企业名称')),
                ('type', models.SmallIntegerField(choices=[(0, '生产企业'), (1, '经销企业'), (2, '零售企业')], verbose_name='企业类别')),
                ('organization_code', models.CharField(max_length=18, verbose_name='社会信用代码')),
                ('address', models.CharField(max_length=50, verbose_name='企业地址')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('notes', models.TextField(verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='FoodInfo',
            fields=[
                ('foodID', models.AutoField(primary_key=True, serialize=False, verbose_name='食品ID')),
                ('name', models.CharField(max_length=16, verbose_name='食品名称')),
                ('permission_code', models.CharField(max_length=16, verbose_name='食品生产许可证编号')),
                ('create_time', models.DateTimeField(verbose_name='登记日期')),
                ('notes', models.TextField(verbose_name='备注')),
                ('enterpriseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.enterpriseinfo')),
            ],
        ),
    ]
