# Generated by Django 4.2 on 2023-04-14 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='成立日期'),
        ),
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='notes',
            field=models.TextField(default='无', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='登记日期'),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='notes',
            field=models.TextField(default='无', verbose_name='备注'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('account_num', models.CharField(max_length=20, verbose_name='账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('type', models.SmallIntegerField(choices=[(0, '超级管理员'), (1, '企业级管理员'), (2, '终端管理员')], verbose_name='用户类别')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('enterpriseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.enterpriseinfo')),
            ],
        ),
    ]
