# Generated by Django 4.2 on 2023-04-17 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_enterpriseinfo_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('deviceID', models.AutoField(primary_key=True, serialize=False, verbose_name='设备ID')),
                ('name', models.CharField(max_length=16, verbose_name='设备名称')),
                ('mac_code', models.CharField(max_length=16, verbose_name='MAC号')),
                ('notes', models.TextField(default='无', verbose_name='备注')),
                ('enterpriseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.enterpriseinfo', verbose_name='所属企业')),
            ],
        ),
        migrations.CreateModel(
            name='FoodbatchInfo',
            fields=[
                ('batchID', models.AutoField(primary_key=True, serialize=False, verbose_name='操作ID')),
                ('manufactureDate', models.DateField(default=django.utils.timezone.now, verbose_name='生产日期')),
                ('expireDate', models.DateField(verbose_name='截止日期')),
            ],
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='enterpriseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.enterpriseinfo', verbose_name='所属企业'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='account_num',
            field=models.CharField(max_length=20, unique=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='enterpriseID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.enterpriseinfo', verbose_name='所属企业'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(\\w)+$', '用户名只能有字母数字下划线组成')], verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(?![a-z]+$)(?![A-Z]+$)(?!\\d+$).{6,20}$', '密码必须包含大写\\小写字母、数字、特殊字符至少两种,且长度在6-20')], verbose_name='密码'),
        ),
        migrations.CreateModel(
            name='SingleFoodInfo',
            fields=[
                ('traceID', models.AutoField(primary_key=True, serialize=False, verbose_name='溯源ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未被验证'), (1, '已被验证')], default=0, verbose_name='防伪状态')),
                ('batchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.foodbatchinfo', verbose_name='批次ID')),
            ],
        ),
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('operateID', models.AutoField(primary_key=True, serialize=False, verbose_name='操作ID')),
                ('operate_datetime', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.deviceinfo', verbose_name='设备ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='负责人')),
            ],
        ),
        migrations.AddField(
            model_name='foodbatchinfo',
            name='foodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.foodinfo', verbose_name='食品ID'),
        ),
        migrations.CreateModel(
            name='FlowRecord',
            fields=[
                ('flowID', models.AutoField(primary_key=True, serialize=False, verbose_name='操作ID')),
                ('record_datetime', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('batchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.foodbatchinfo', verbose_name='批次ID')),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.deviceinfo', verbose_name='设备ID')),
            ],
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='负责人'),
        ),
    ]
