# Generated by Django 4.2 on 2023-04-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_deviceinfo_foodbatchinfo_alter_foodinfo_enterpriseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationrecord',
            name='notes',
            field=models.TextField(default='添加', verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='flowrecord',
            name='batchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.foodbatchinfo', verbose_name='食品批次'),
        ),
        migrations.AlterField(
            model_name='flowrecord',
            name='deviceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.deviceinfo', verbose_name='操作设备'),
        ),
        migrations.AlterField(
            model_name='flowrecord',
            name='flowID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='周转ID'),
        ),
        migrations.AlterField(
            model_name='foodbatchinfo',
            name='batchID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='批次ID'),
        ),
        migrations.AlterField(
            model_name='foodbatchinfo',
            name='foodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.foodinfo', verbose_name='关联食品'),
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='deviceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.deviceinfo', verbose_name='操作设备'),
        ),
        migrations.AlterField(
            model_name='singlefoodinfo',
            name='batchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.foodbatchinfo', verbose_name='食品批次'),
        ),
    ]
