# Generated by Django 4.2 on 2023-04-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_operationrecord_notes_alter_flowrecord_batchid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrecord',
            name='enterpriseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.enterpriseinfo', verbose_name='所属企业'),
        ),
        migrations.AddField(
            model_name='flowrecord',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='负责人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationrecord',
            name='notes',
            field=models.TextField(default='添加周转记录', verbose_name='操作内容'),
        ),
    ]
