# Generated by Django 4.2 on 2023-04-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_foodinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefoodinfo',
            name='foodID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.foodinfo', verbose_name='关联食品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowrecord',
            name='enterpriseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.enterpriseinfo', verbose_name='目的企业'),
        ),
        migrations.CreateModel(
            name='FoodMaterialInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='app01.foodinfo', verbose_name='原材料')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app01.foodinfo', verbose_name='产品')),
            ],
        ),
    ]
