# Generated by Django 4.2 on 2023-04-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_singlefoodinfo_foodid_alter_flowrecord_enterpriseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrecord',
            name='foodID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.foodinfo', verbose_name='关联食品'),
            preserve_default=False,
        ),
    ]
