# Generated by Django 4.2 on 2023-04-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_flowrecord_foodid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodMaterialInfo',
            new_name='MaterialInfo',
        ),
    ]
