# Generated by Django 4.2 on 2023-04-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_remove_foodinfo_permission_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlefoodinfo',
            name='weight',
        ),
        migrations.AddField(
            model_name='foodinfo',
            name='chemical_addition',
            field=models.TextField(default='无', verbose_name='化学食品添加剂'),
        ),
        migrations.AddField(
            model_name='foodinfo',
            name='nutrition_table',
            field=models.TextField(default='无', verbose_name='营养成分表'),
        ),
        migrations.AddField(
            model_name='foodinfo',
            name='weight',
            field=models.CharField(default='0', max_length=50, verbose_name='产品单品重量'),
        ),
        migrations.AlterField(
            model_name='foodbatchinfo',
            name='quality',
            field=models.TextField(default='无', verbose_name='食品质量验收信息'),
        ),
    ]
