# Generated by Django 4.2 on 2023-04-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_remove_singlefoodinfo_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='address',
            field=models.TextField(default='无', verbose_name='企业地址'),
        ),
    ]
