# Generated by Django 4.2 on 2023-05-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_enterpriseinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrecord',
            name='quality',
            field=models.TextField(default='无', verbose_name='品质检验信息'),
        ),
        migrations.AlterField(
            model_name='foodbatchinfo',
            name='quality',
            field=models.TextField(default='无', verbose_name='品质检验信息'),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='weight',
            field=models.CharField(default='0', max_length=50, verbose_name='净含量'),
        ),
    ]
