# Generated by Django 4.2 on 2025-04-09 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_flowrecord_quality_alter_foodbatchinfo_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrecord',
            name='batchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.foodbatchinfo', verbose_name='生产批次号'),
        ),
        migrations.AlterField(
            model_name='flowrecord',
            name='quality',
            field=models.TextField(default='无', verbose_name='质检结果'),
        ),
        migrations.AlterField(
            model_name='foodbatchinfo',
            name='batchID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='批次号'),
        ),
        migrations.AlterField(
            model_name='foodbatchinfo',
            name='quality',
            field=models.TextField(default='无', verbose_name='抽检结果'),
        ),
        migrations.AlterField(
            model_name='materialinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='关联ID'),
        ),
        migrations.AlterField(
            model_name='materialinfo',
            name='material_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_batch', to='app01.foodbatchinfo', verbose_name='原材料批次号'),
        ),
        migrations.AlterField(
            model_name='materialinfo',
            name='product_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_batch', to='app01.foodbatchinfo', verbose_name='产品批次号'),
        ),
        migrations.AlterField(
            model_name='singlefoodinfo',
            name='batchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.foodbatchinfo', verbose_name='生产批次号'),
        ),
        migrations.AlterField(
            model_name='singlefoodinfo',
            name='traceID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='溯源码'),
        ),
    ]
